### ISSUE TITLE
首页的春黑gif无法显示

### ISSUE THREAD

**Issue by IgNit3R** [CJowo/pcr-guild-django#11]
右键看下页面源码
![1](https://user-images.githubusercontent.com/67913229/88374164-3e49b480-cdd4-11ea-89e9-38bf33b99b02.png)

后端看见代码有更新就顺手pull了，前端直接把项目拉下来自己build完后好像少了春黑的gif.

**Comment by IgNit3R** [comment]
不太确定是我pull了后端的影响还是前端的问题

**Comment by CJowo** [comment]
我把它删了，因为太大了占带宽..
