### ISSUE TITLE
腾讯QQ上有人在售卖您的代码

### ISSUE THREAD

**Issue by Xueji1998** [CJowo/pcr-guild-django#7]
QQ群 665303699 里，用户 799165967 和用户 653445146 正在售卖您的代码

**Comment by CJowo** [comment]
啊这… 方便提供一下证据吗

**Comment by Xueji1998** [comment]
对不起，我刚发现您的代码是群员上传的。打扰到您不好意思
![1F8D8D4C847B14E2B76602D64F752BC8](https://user-images.githubusercontent.com/51162527/84619973-4545f300-af09-11ea-8333-ac1d594801ec.JPG)
